fix manage polluting the environment

diff --git a/common/manage b/common/manage
--- a/common/manage
+++ b/common/manage
@@ -1,5 +1,4 @@
 #!/usr/bin/env bash
-
 [[ $MANAGE_LOADED ]] && return
 
 source collection-shell
@@ -7,6 +6,20 @@ source collection-string
 source collection-message
 source collection-tag
 source collection-array
+
+_mExceptionHandler () {
+    local trap_name="$1"
+    echo "ERROR: ${trap_name} on line $( caller )" >&2 ; _exit 1
+}
+
+_mCatchExceptions () {
+    trap '_exceptionHandler "SIGERR" ${LINENO} ${$?}' ERR
+    trap '_exceptionHandler "SIGINT" ${LINENO} ${$?}' INT
+    trap '_exceptionHandler "SIGHUP" ${LINENO} ${$?}' HUP
+    trap '_exceptionHandler "SIGTERM "${LINENO} ${$?}' TERM
+    trap '_exceptionHandler "SIGKILL" ${LINENO} ${$?}' KILL
+    trap '_exceptionHandler "SIGQUIT" ${LINENO} ${$?}' QUIT
+}
 
 _topicExists () {
     _includes _topicNames "$*"
@@ -137,23 +150,24 @@ _wrapper () {
     shift
 
     MANAGETOPIC="${topic}"
-    MANAGEIMPORTS="$(_embeddedTag "import" "${path}")"
+    MANAGEIMPORTS="$(_embeddedTag "import" "${path}" |tr '\n' ' ')"
 
     export MANAGEIMPORTS
     export MANAGETOPIC
 
     bashcommand="$(echo -n \
-                   VERBOSE="${VERBOSE}" \
-                   MANAGEDIRECTORY="${MANAGEDIRECTORY}" \
-                   MANAGEINIT="${MANAGEINIT}" \
-                   MANAGETOPIC="${MANAGETOPIC}" \
-                   MANAGEIMPORTS=\""${MANAGEIMPORTS}"\" \
-                   source "${MANAGEPATH}" \&\& \
-                   source "${path}" \&\& \
+                   MANAGEVERBOSE=\""${MANAGEVERBOSE}"\" \&\& \
+                   MANAGEDIRECTORY=\""${MANAGEDIRECTORY}"\" \&\& \
+                   MANAGEINIT=\""${MANAGEINIT}"\" \&\& \
+                   MANAGETOPIC=\""${MANAGETOPIC}"\" \&\& \
+                   MANAGEIMPORTS=\""${MANAGEIMPORTS}"\" \&\& \
+                   . "${MANAGEPATH}" \&\& \
+                   . "${path}" \&\& \
                    "main" "$@"
                  )"
 
-    bash --noprofile -ic "${bashcommand}"
+    _cleanup
+    bash --noprofile -ic "${bashcommand}" || _exit
 }
 
 _run () {
@@ -166,13 +180,14 @@ _run () {
     else
         _usage
     fi
+    _cleanup
 }
 
 _flags () {
     case $@ in
         h|\?)
             _usage "${OPTARG}"
-            exit 0
+            _exit 0
             ;;
         v)
             _verbose 1
@@ -181,10 +196,10 @@ _flags () {
             if [ "${OPTARG}" == "h" ]
             then
                 _usage
-                exit 0
+                _exit 0
             else
                 echo "Option -$OPTARG requires an argument." >&2
-                exit 1
+                _exit 1
             fi
             ;;
     esac
